// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: pb_util_test.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Kudu.Client.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class TestSecurePrintingPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"insecure1")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Insecure1
        {
            get { return __pbn__Insecure1 ?? ""; }
            set { __pbn__Insecure1 = value; }
        }
        public bool ShouldSerializeInsecure1() => __pbn__Insecure1 != null;
        public void ResetInsecure1() => __pbn__Insecure1 = null;
        private string __pbn__Insecure1;

        [global::ProtoBuf.ProtoMember(2, Name = @"secure1")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Secure1
        {
            get { return __pbn__Secure1 ?? ""; }
            set { __pbn__Secure1 = value; }
        }
        public bool ShouldSerializeSecure1() => __pbn__Secure1 != null;
        public void ResetSecure1() => __pbn__Secure1 = null;
        private string __pbn__Secure1;

        [global::ProtoBuf.ProtoMember(3, Name = @"insecure2")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Insecure2
        {
            get { return __pbn__Insecure2 ?? ""; }
            set { __pbn__Insecure2 = value; }
        }
        public bool ShouldSerializeInsecure2() => __pbn__Insecure2 != null;
        public void ResetInsecure2() => __pbn__Insecure2 = null;
        private string __pbn__Insecure2;

        [global::ProtoBuf.ProtoMember(4, Name = @"secure2")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Secure2
        {
            get { return __pbn__Secure2 ?? ""; }
            set { __pbn__Secure2 = value; }
        }
        public bool ShouldSerializeSecure2() => __pbn__Secure2 != null;
        public void ResetSecure2() => __pbn__Secure2 = null;
        private string __pbn__Secure2;

        [global::ProtoBuf.ProtoMember(5, Name = @"repeated_secure")]
        public global::System.Collections.Generic.List<string> RepeatedSecures { get; } = new global::System.Collections.Generic.List<string>();

        [global::ProtoBuf.ProtoMember(6, Name = @"insecure3")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Insecure3
        {
            get { return __pbn__Insecure3 ?? ""; }
            set { __pbn__Insecure3 = value; }
        }
        public bool ShouldSerializeInsecure3() => __pbn__Insecure3 != null;
        public void ResetInsecure3() => __pbn__Insecure3 = null;
        private string __pbn__Insecure3;

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
