// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: rpc_header.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Kudu.Client.Protocol.Rpc
{

    [global::ProtoBuf.ProtoContract()]
    public partial class UserInformationPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"effective_user")]
        [global::System.ComponentModel.DefaultValue("")]
        public string EffectiveUser
        {
            get { return __pbn__EffectiveUser ?? ""; }
            set { __pbn__EffectiveUser = value; }
        }
        public bool ShouldSerializeEffectiveUser() => __pbn__EffectiveUser != null;
        public void ResetEffectiveUser() => __pbn__EffectiveUser = null;
        private string __pbn__EffectiveUser;

        [global::ProtoBuf.ProtoMember(2, Name = @"real_user", IsRequired = true)]
        public string RealUser { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConnectionContextPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"DEPRECATED_user_info")]
        public UserInformationPB DEPRECATEDuserinfo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"encoded_nonce")]
        public byte[] EncodedNonce
        {
            get { return __pbn__EncodedNonce; }
            set { __pbn__EncodedNonce = value; }
        }
        public bool ShouldSerializeEncodedNonce() => __pbn__EncodedNonce != null;
        public void ResetEncodedNonce() => __pbn__EncodedNonce = null;
        private byte[] __pbn__EncodedNonce;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AuthenticationTypePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1)]
        public Sasl sasl
        {
            get { return __pbn__type.Is(1) ? ((Sasl)__pbn__type.Object) : default; }
            set { __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(1, value); }
        }
        public bool ShouldSerializesasl() => __pbn__type.Is(1);
        public void Resetsasl() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 1);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__type;

        [global::ProtoBuf.ProtoMember(2)]
        public Token token
        {
            get { return __pbn__type.Is(2) ? ((Token)__pbn__type.Object) : default; }
            set { __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializetoken() => __pbn__type.Is(2);
        public void Resettoken() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 2);

        [global::ProtoBuf.ProtoMember(3)]
        public Certificate certificate
        {
            get { return __pbn__type.Is(3) ? ((Certificate)__pbn__type.Object) : default; }
            set { __pbn__type = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializecertificate() => __pbn__type.Is(3);
        public void Resetcertificate() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__type, 3);

        [global::ProtoBuf.ProtoContract()]
        public partial class Sasl : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Token : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Certificate : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NegotiatePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"supported_features")]
        public global::System.Collections.Generic.List<RpcFeatureFlag> SupportedFeatures { get; } = new global::System.Collections.Generic.List<RpcFeatureFlag>();

        [global::ProtoBuf.ProtoMember(2, Name = @"step", IsRequired = true)]
        public NegotiateStep Step { get; set; } = NegotiateStep.Unknown;

        [global::ProtoBuf.ProtoMember(3, Name = @"token")]
        public byte[] Token
        {
            get { return __pbn__Token; }
            set { __pbn__Token = value; }
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private byte[] __pbn__Token;

        [global::ProtoBuf.ProtoMember(5, Name = @"tls_handshake")]
        public byte[] TlsHandshake
        {
            get { return __pbn__TlsHandshake; }
            set { __pbn__TlsHandshake = value; }
        }
        public bool ShouldSerializeTlsHandshake() => __pbn__TlsHandshake != null;
        public void ResetTlsHandshake() => __pbn__TlsHandshake = null;
        private byte[] __pbn__TlsHandshake;

        [global::ProtoBuf.ProtoMember(6, Name = @"channel_bindings")]
        public byte[] ChannelBindings
        {
            get { return __pbn__ChannelBindings; }
            set { __pbn__ChannelBindings = value; }
        }
        public bool ShouldSerializeChannelBindings() => __pbn__ChannelBindings != null;
        public void ResetChannelBindings() => __pbn__ChannelBindings = null;
        private byte[] __pbn__ChannelBindings;

        [global::ProtoBuf.ProtoMember(9, Name = @"nonce")]
        public byte[] Nonce
        {
            get { return __pbn__Nonce; }
            set { __pbn__Nonce = value; }
        }
        public bool ShouldSerializeNonce() => __pbn__Nonce != null;
        public void ResetNonce() => __pbn__Nonce = null;
        private byte[] __pbn__Nonce;

        [global::ProtoBuf.ProtoMember(4, Name = @"sasl_mechanisms")]
        public global::System.Collections.Generic.List<SaslMechanism> SaslMechanisms { get; } = new global::System.Collections.Generic.List<SaslMechanism>();

        [global::ProtoBuf.ProtoMember(7, Name = @"authn_types")]
        public global::System.Collections.Generic.List<AuthenticationTypePB> AuthnTypes { get; } = new global::System.Collections.Generic.List<AuthenticationTypePB>();

        [global::ProtoBuf.ProtoMember(8, Name = @"authn_token")]
        public global::Kudu.Client.Protocol.Security.SignedTokenPB AuthnToken { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class SaslMechanism : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(2, Name = @"mechanism", IsRequired = true)]
            public string Mechanism { get; set; }

        }

        [global::ProtoBuf.ProtoContract()]
        public enum NegotiateStep
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 999,
            [global::ProtoBuf.ProtoEnum(Name = @"NEGOTIATE")]
            Negotiate = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"SASL_SUCCESS")]
            SaslSuccess = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"SASL_INITIATE")]
            SaslInitiate = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"SASL_CHALLENGE")]
            SaslChallenge = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"SASL_RESPONSE")]
            SaslResponse = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"TLS_HANDSHAKE")]
            TlsHandshake = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"TOKEN_EXCHANGE")]
            TokenExchange = 6,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RemoteMethodPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"service_name", IsRequired = true)]
        public string ServiceName { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"method_name", IsRequired = true)]
        public string MethodName { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestIdPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"client_id", IsRequired = true)]
        public string ClientId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"seq_no", IsRequired = true)]
        public long SeqNo { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"first_incomplete_seq_no", IsRequired = true)]
        public long FirstIncompleteSeqNo { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"attempt_no", IsRequired = true)]
        public long AttemptNo { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RequestHeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(3, Name = @"call_id", IsRequired = true)]
        public int CallId { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"remote_method")]
        public RemoteMethodPB RemoteMethod { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"timeout_millis")]
        public uint TimeoutMillis
        {
            get { return __pbn__TimeoutMillis.GetValueOrDefault(); }
            set { __pbn__TimeoutMillis = value; }
        }
        public bool ShouldSerializeTimeoutMillis() => __pbn__TimeoutMillis != null;
        public void ResetTimeoutMillis() => __pbn__TimeoutMillis = null;
        private uint? __pbn__TimeoutMillis;

        [global::ProtoBuf.ProtoMember(11, Name = @"required_feature_flags")]
        public uint[] RequiredFeatureFlags { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"request_id")]
        public RequestIdPB RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"sidecar_offsets")]
        public uint[] SidecarOffsets { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ResponseHeader : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"call_id", IsRequired = true)]
        public int CallId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"is_error")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IsError
        {
            get { return __pbn__IsError ?? false; }
            set { __pbn__IsError = value; }
        }
        public bool ShouldSerializeIsError() => __pbn__IsError != null;
        public void ResetIsError() => __pbn__IsError = null;
        private bool? __pbn__IsError;

        [global::ProtoBuf.ProtoMember(3, Name = @"sidecar_offsets")]
        public uint[] SidecarOffsets { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ErrorStatusPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"message", IsRequired = true)]
        public string Message { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"code")]
        [global::System.ComponentModel.DefaultValue(RpcErrorCodePB.FatalUnknown)]
        public RpcErrorCodePB Code
        {
            get { return __pbn__Code ?? RpcErrorCodePB.FatalUnknown; }
            set { __pbn__Code = value; }
        }
        public bool ShouldSerializeCode() => __pbn__Code != null;
        public void ResetCode() => __pbn__Code = null;
        private RpcErrorCodePB? __pbn__Code;

        [global::ProtoBuf.ProtoMember(3, Name = @"unsupported_feature_flags")]
        public uint[] UnsupportedFeatureFlags { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum RpcErrorCodePB
        {
            [global::ProtoBuf.ProtoEnum(Name = @"FATAL_UNKNOWN")]
            FatalUnknown = 10,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR_APPLICATION")]
            ErrorApplication = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR_NO_SUCH_METHOD")]
            ErrorNoSuchMethod = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR_NO_SUCH_SERVICE")]
            ErrorNoSuchService = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR_SERVER_TOO_BUSY")]
            ErrorServerTooBusy = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR_INVALID_REQUEST")]
            ErrorInvalidRequest = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR_REQUEST_STALE")]
            ErrorRequestStale = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR_UNAVAILABLE")]
            ErrorUnavailable = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"ERROR_INVALID_AUTHORIZATION_TOKEN")]
            ErrorInvalidAuthorizationToken = 17,
            [global::ProtoBuf.ProtoEnum(Name = @"FATAL_SERVER_SHUTTING_DOWN")]
            FatalServerShuttingDown = 11,
            [global::ProtoBuf.ProtoEnum(Name = @"FATAL_INVALID_RPC_HEADER")]
            FatalInvalidRpcHeader = 12,
            [global::ProtoBuf.ProtoEnum(Name = @"FATAL_DESERIALIZING_REQUEST")]
            FatalDeserializingRequest = 13,
            [global::ProtoBuf.ProtoEnum(Name = @"FATAL_VERSION_MISMATCH")]
            FatalVersionMismatch = 14,
            [global::ProtoBuf.ProtoEnum(Name = @"FATAL_UNAUTHORIZED")]
            FatalUnauthorized = 15,
            [global::ProtoBuf.ProtoEnum(Name = @"FATAL_INVALID_AUTHENTICATION_TOKEN")]
            FatalInvalidAuthenticationToken = 16,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum RpcFeatureFlag
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
        Unknown = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"APPLICATION_FEATURE_FLAGS")]
        ApplicationFeatureFlags = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"TLS")]
        Tls = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"TLS_AUTHENTICATION_ONLY")]
        TlsAuthenticationOnly = 3,
    }
}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
