// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: histogram.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Knet.Kudu.Client.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class HistogramSnapshotPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"type", IsRequired = true)]
        public string Type { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"description")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Description
        {
            get { return __pbn__Description ?? ""; }
            set { __pbn__Description = value; }
        }
        public bool ShouldSerializeDescription() => __pbn__Description != null;
        public void ResetDescription() => __pbn__Description = null;
        private string __pbn__Description;

        [global::ProtoBuf.ProtoMember(4, Name = @"unit", IsRequired = true)]
        public string Unit { get; set; }

        [global::ProtoBuf.ProtoMember(19, Name = @"label")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Label
        {
            get { return __pbn__Label ?? ""; }
            set { __pbn__Label = value; }
        }
        public bool ShouldSerializeLabel() => __pbn__Label != null;
        public void ResetLabel() => __pbn__Label = null;
        private string __pbn__Label;

        [global::ProtoBuf.ProtoMember(5, Name = @"max_trackable_value", IsRequired = true)]
        public ulong MaxTrackableValue { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"num_significant_digits", IsRequired = true)]
        public int NumSignificantDigits { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"total_count", IsRequired = true)]
        public ulong TotalCount { get; set; }

        [global::ProtoBuf.ProtoMember(18, Name = @"total_sum")]
        public ulong TotalSum
        {
            get { return __pbn__TotalSum.GetValueOrDefault(); }
            set { __pbn__TotalSum = value; }
        }
        public bool ShouldSerializeTotalSum() => __pbn__TotalSum != null;
        public void ResetTotalSum() => __pbn__TotalSum = null;
        private ulong? __pbn__TotalSum;

        [global::ProtoBuf.ProtoMember(8, Name = @"min", IsRequired = true)]
        public ulong Min { get; set; }

        [global::ProtoBuf.ProtoMember(9, Name = @"mean", IsRequired = true)]
        public double Mean { get; set; }

        [global::ProtoBuf.ProtoMember(10, Name = @"percentile_75", IsRequired = true)]
        public ulong Percentile75 { get; set; }

        [global::ProtoBuf.ProtoMember(11, Name = @"percentile_95", IsRequired = true)]
        public ulong Percentile95 { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"percentile_99", IsRequired = true)]
        public ulong Percentile99 { get; set; }

        [global::ProtoBuf.ProtoMember(13, Name = @"percentile_99_9", IsRequired = true)]
        public ulong Percentile999 { get; set; }

        [global::ProtoBuf.ProtoMember(14, Name = @"percentile_99_99", IsRequired = true)]
        public ulong Percentile9999 { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"max", IsRequired = true)]
        public ulong Max { get; set; }

        [global::ProtoBuf.ProtoMember(16, Name = @"values", IsPacked = true)]
        public ulong[] Values { get; set; }

        [global::ProtoBuf.ProtoMember(17, Name = @"counts", IsPacked = true)]
        public ulong[] Counts { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HistogramSnapshotsListPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"histograms")]
        public global::System.Collections.Generic.List<HistogramSnapshotPB> Histograms { get; } = new global::System.Collections.Generic.List<HistogramSnapshotPB>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
