// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: tserver_service.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Knet.Kudu.Client.Protocol.Tserver
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ChecksumRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"new_request")]
        public NewScanRequestPB NewRequest { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"continue_request")]
        public ContinueChecksumRequestPB ContinueRequest { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"call_seq_id")]
        public uint CallSeqId
        {
            get { return __pbn__CallSeqId.GetValueOrDefault(); }
            set { __pbn__CallSeqId = value; }
        }
        public bool ShouldSerializeCallSeqId() => __pbn__CallSeqId != null;
        public void ResetCallSeqId() => __pbn__CallSeqId = null;
        private uint? __pbn__CallSeqId;

        [global::ProtoBuf.ProtoMember(4, Name = @"batch_size_bytes")]
        public uint BatchSizeBytes
        {
            get { return __pbn__BatchSizeBytes.GetValueOrDefault(); }
            set { __pbn__BatchSizeBytes = value; }
        }
        public bool ShouldSerializeBatchSizeBytes() => __pbn__BatchSizeBytes != null;
        public void ResetBatchSizeBytes() => __pbn__BatchSizeBytes = null;
        private uint? __pbn__BatchSizeBytes;

        [global::ProtoBuf.ProtoMember(5, Name = @"close_scanner")]
        public bool CloseScanner
        {
            get { return __pbn__CloseScanner.GetValueOrDefault(); }
            set { __pbn__CloseScanner = value; }
        }
        public bool ShouldSerializeCloseScanner() => __pbn__CloseScanner != null;
        public void ResetCloseScanner() => __pbn__CloseScanner = null;
        private bool? __pbn__CloseScanner;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ContinueChecksumRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"scanner_id", IsRequired = true)]
        public byte[] ScannerId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"previous_checksum", IsRequired = true)]
        public ulong PreviousChecksum { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChecksumResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        public TabletServerErrorPB Error { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"checksum")]
        public ulong Checksum
        {
            get { return __pbn__Checksum.GetValueOrDefault(); }
            set { __pbn__Checksum = value; }
        }
        public bool ShouldSerializeChecksum() => __pbn__Checksum != null;
        public void ResetChecksum() => __pbn__Checksum = null;
        private ulong? __pbn__Checksum;

        [global::ProtoBuf.ProtoMember(3, Name = @"scanner_id")]
        public byte[] ScannerId
        {
            get { return __pbn__ScannerId; }
            set { __pbn__ScannerId = value; }
        }
        public bool ShouldSerializeScannerId() => __pbn__ScannerId != null;
        public void ResetScannerId() => __pbn__ScannerId = null;
        private byte[] __pbn__ScannerId;

        [global::ProtoBuf.ProtoMember(4, Name = @"has_more_results")]
        public bool HasMoreResults
        {
            get { return __pbn__HasMoreResults.GetValueOrDefault(); }
            set { __pbn__HasMoreResults = value; }
        }
        public bool ShouldSerializeHasMoreResults() => __pbn__HasMoreResults != null;
        public void ResetHasMoreResults() => __pbn__HasMoreResults = null;
        private bool? __pbn__HasMoreResults;

        [global::ProtoBuf.ProtoMember(5, Name = @"snap_timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SnapTimestamp
        {
            get { return __pbn__SnapTimestamp.GetValueOrDefault(); }
            set { __pbn__SnapTimestamp = value; }
        }
        public bool ShouldSerializeSnapTimestamp() => __pbn__SnapTimestamp != null;
        public void ResetSnapTimestamp() => __pbn__SnapTimestamp = null;
        private ulong? __pbn__SnapTimestamp;

        [global::ProtoBuf.ProtoMember(6, Name = @"rows_checksummed")]
        public long RowsChecksummed
        {
            get { return __pbn__RowsChecksummed.GetValueOrDefault(); }
            set { __pbn__RowsChecksummed = value; }
        }
        public bool ShouldSerializeRowsChecksummed() => __pbn__RowsChecksummed != null;
        public void ResetRowsChecksummed() => __pbn__RowsChecksummed = null;
        private long? __pbn__RowsChecksummed;

        [global::ProtoBuf.ProtoMember(7, Name = @"resource_metrics")]
        public ResourceMetricsPB ResourceMetrics { get; set; }

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
