// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: common.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Knet.Kudu.Client.Protocol
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ColumnTypeAttributesPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"precision")]
        public int Precision
        {
            get { return __pbn__Precision.GetValueOrDefault(); }
            set { __pbn__Precision = value; }
        }
        public bool ShouldSerializePrecision() => __pbn__Precision != null;
        public void ResetPrecision() => __pbn__Precision = null;
        private int? __pbn__Precision;

        [global::ProtoBuf.ProtoMember(2, Name = @"scale")]
        public int Scale
        {
            get { return __pbn__Scale.GetValueOrDefault(); }
            set { __pbn__Scale = value; }
        }
        public bool ShouldSerializeScale() => __pbn__Scale != null;
        public void ResetScale() => __pbn__Scale = null;
        private int? __pbn__Scale;

        [global::ProtoBuf.ProtoMember(3, Name = @"length")]
        public int Length
        {
            get { return __pbn__Length.GetValueOrDefault(); }
            set { __pbn__Length = value; }
        }
        public bool ShouldSerializeLength() => __pbn__Length != null;
        public void ResetLength() => __pbn__Length = null;
        private int? __pbn__Length;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ColumnSchemaPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id")]
        public uint Id
        {
            get { return __pbn__Id.GetValueOrDefault(); }
            set { __pbn__Id = value; }
        }
        public bool ShouldSerializeId() => __pbn__Id != null;
        public void ResetId() => __pbn__Id = null;
        private uint? __pbn__Id;

        [global::ProtoBuf.ProtoMember(2, Name = @"name", IsRequired = true)]
        public string Name { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"type", IsRequired = true)]
        public DataTypePB Type { get; set; } = DataTypePB.UnknownData;

        [global::ProtoBuf.ProtoMember(4, Name = @"is_key")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IsKey
        {
            get { return __pbn__IsKey ?? false; }
            set { __pbn__IsKey = value; }
        }
        public bool ShouldSerializeIsKey() => __pbn__IsKey != null;
        public void ResetIsKey() => __pbn__IsKey = null;
        private bool? __pbn__IsKey;

        [global::ProtoBuf.ProtoMember(5, Name = @"is_nullable")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IsNullable
        {
            get { return __pbn__IsNullable ?? false; }
            set { __pbn__IsNullable = value; }
        }
        public bool ShouldSerializeIsNullable() => __pbn__IsNullable != null;
        public void ResetIsNullable() => __pbn__IsNullable = null;
        private bool? __pbn__IsNullable;

        [global::ProtoBuf.ProtoMember(6, Name = @"read_default_value")]
        public byte[] ReadDefaultValue
        {
            get { return __pbn__ReadDefaultValue; }
            set { __pbn__ReadDefaultValue = value; }
        }
        public bool ShouldSerializeReadDefaultValue() => __pbn__ReadDefaultValue != null;
        public void ResetReadDefaultValue() => __pbn__ReadDefaultValue = null;
        private byte[] __pbn__ReadDefaultValue;

        [global::ProtoBuf.ProtoMember(7, Name = @"write_default_value")]
        public byte[] WriteDefaultValue
        {
            get { return __pbn__WriteDefaultValue; }
            set { __pbn__WriteDefaultValue = value; }
        }
        public bool ShouldSerializeWriteDefaultValue() => __pbn__WriteDefaultValue != null;
        public void ResetWriteDefaultValue() => __pbn__WriteDefaultValue = null;
        private byte[] __pbn__WriteDefaultValue;

        [global::ProtoBuf.ProtoMember(8, Name = @"encoding")]
        [global::System.ComponentModel.DefaultValue(EncodingTypePB.AutoEncoding)]
        public EncodingTypePB Encoding
        {
            get { return __pbn__Encoding ?? EncodingTypePB.AutoEncoding; }
            set { __pbn__Encoding = value; }
        }
        public bool ShouldSerializeEncoding() => __pbn__Encoding != null;
        public void ResetEncoding() => __pbn__Encoding = null;
        private EncodingTypePB? __pbn__Encoding;

        [global::ProtoBuf.ProtoMember(9, Name = @"compression")]
        [global::System.ComponentModel.DefaultValue(CompressionTypePB.DefaultCompression)]
        public CompressionTypePB Compression
        {
            get { return __pbn__Compression ?? CompressionTypePB.DefaultCompression; }
            set { __pbn__Compression = value; }
        }
        public bool ShouldSerializeCompression() => __pbn__Compression != null;
        public void ResetCompression() => __pbn__Compression = null;
        private CompressionTypePB? __pbn__Compression;

        [global::ProtoBuf.ProtoMember(10, Name = @"cfile_block_size")]
        [global::System.ComponentModel.DefaultValue(0)]
        public int CfileBlockSize
        {
            get { return __pbn__CfileBlockSize ?? 0; }
            set { __pbn__CfileBlockSize = value; }
        }
        public bool ShouldSerializeCfileBlockSize() => __pbn__CfileBlockSize != null;
        public void ResetCfileBlockSize() => __pbn__CfileBlockSize = null;
        private int? __pbn__CfileBlockSize;

        [global::ProtoBuf.ProtoMember(11, Name = @"type_attributes")]
        public ColumnTypeAttributesPB TypeAttributes { get; set; }

        [global::ProtoBuf.ProtoMember(12, Name = @"comment")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Comment
        {
            get { return __pbn__Comment ?? ""; }
            set { __pbn__Comment = value; }
        }
        public bool ShouldSerializeComment() => __pbn__Comment != null;
        public void ResetComment() => __pbn__Comment = null;
        private string __pbn__Comment;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ColumnSchemaDeltaPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Name
        {
            get { return __pbn__Name ?? ""; }
            set { __pbn__Name = value; }
        }
        public bool ShouldSerializeName() => __pbn__Name != null;
        public void ResetName() => __pbn__Name = null;
        private string __pbn__Name;

        [global::ProtoBuf.ProtoMember(2, Name = @"new_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NewName
        {
            get { return __pbn__NewName ?? ""; }
            set { __pbn__NewName = value; }
        }
        public bool ShouldSerializeNewName() => __pbn__NewName != null;
        public void ResetNewName() => __pbn__NewName = null;
        private string __pbn__NewName;

        [global::ProtoBuf.ProtoMember(4, Name = @"default_value")]
        public byte[] DefaultValue
        {
            get { return __pbn__DefaultValue; }
            set { __pbn__DefaultValue = value; }
        }
        public bool ShouldSerializeDefaultValue() => __pbn__DefaultValue != null;
        public void ResetDefaultValue() => __pbn__DefaultValue = null;
        private byte[] __pbn__DefaultValue;

        [global::ProtoBuf.ProtoMember(5, Name = @"remove_default")]
        public bool RemoveDefault
        {
            get { return __pbn__RemoveDefault.GetValueOrDefault(); }
            set { __pbn__RemoveDefault = value; }
        }
        public bool ShouldSerializeRemoveDefault() => __pbn__RemoveDefault != null;
        public void ResetRemoveDefault() => __pbn__RemoveDefault = null;
        private bool? __pbn__RemoveDefault;

        [global::ProtoBuf.ProtoMember(6, Name = @"encoding")]
        [global::System.ComponentModel.DefaultValue(EncodingTypePB.UnknownEncoding)]
        public EncodingTypePB Encoding
        {
            get { return __pbn__Encoding ?? EncodingTypePB.UnknownEncoding; }
            set { __pbn__Encoding = value; }
        }
        public bool ShouldSerializeEncoding() => __pbn__Encoding != null;
        public void ResetEncoding() => __pbn__Encoding = null;
        private EncodingTypePB? __pbn__Encoding;

        [global::ProtoBuf.ProtoMember(7, Name = @"compression")]
        [global::System.ComponentModel.DefaultValue(CompressionTypePB.UnknownCompression)]
        public CompressionTypePB Compression
        {
            get { return __pbn__Compression ?? CompressionTypePB.UnknownCompression; }
            set { __pbn__Compression = value; }
        }
        public bool ShouldSerializeCompression() => __pbn__Compression != null;
        public void ResetCompression() => __pbn__Compression = null;
        private CompressionTypePB? __pbn__Compression;

        [global::ProtoBuf.ProtoMember(8, Name = @"block_size")]
        public int BlockSize
        {
            get { return __pbn__BlockSize.GetValueOrDefault(); }
            set { __pbn__BlockSize = value; }
        }
        public bool ShouldSerializeBlockSize() => __pbn__BlockSize != null;
        public void ResetBlockSize() => __pbn__BlockSize = null;
        private int? __pbn__BlockSize;

        [global::ProtoBuf.ProtoMember(9, Name = @"new_comment")]
        [global::System.ComponentModel.DefaultValue("")]
        public string NewComment
        {
            get { return __pbn__NewComment ?? ""; }
            set { __pbn__NewComment = value; }
        }
        public bool ShouldSerializeNewComment() => __pbn__NewComment != null;
        public void ResetNewComment() => __pbn__NewComment = null;
        private string __pbn__NewComment;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SchemaPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"columns")]
        public global::System.Collections.Generic.List<ColumnSchemaPB> Columns { get; } = new global::System.Collections.Generic.List<ColumnSchemaPB>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HostPortPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"host", IsRequired = true)]
        public string Host { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"port", IsRequired = true)]
        public uint Port { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PartitionSchemaPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash_bucket_schemas")]
        public global::System.Collections.Generic.List<HashBucketSchemaPB> HashBucketSchemas { get; } = new global::System.Collections.Generic.List<HashBucketSchemaPB>();

        [global::ProtoBuf.ProtoMember(2, Name = @"range_schema")]
        public RangeSchemaPB RangeSchema { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class ColumnIdentifierPB : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"id")]
            public int Id
            {
                get { return __pbn__identifier.Is(1) ? __pbn__identifier.Int32 : default; }
                set { __pbn__identifier = new global::ProtoBuf.DiscriminatedUnion32Object(1, value); }
            }
            public bool ShouldSerializeId() => __pbn__identifier.Is(1);
            public void ResetId() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__identifier, 1);

            private global::ProtoBuf.DiscriminatedUnion32Object __pbn__identifier;

            [global::ProtoBuf.ProtoMember(2, Name = @"name")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Name
            {
                get { return __pbn__identifier.Is(2) ? ((string)__pbn__identifier.Object) : ""; }
                set { __pbn__identifier = new global::ProtoBuf.DiscriminatedUnion32Object(2, value); }
            }
            public bool ShouldSerializeName() => __pbn__identifier.Is(2);
            public void ResetName() => global::ProtoBuf.DiscriminatedUnion32Object.Reset(ref __pbn__identifier, 2);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class RangeSchemaPB : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"columns")]
            public global::System.Collections.Generic.List<PartitionSchemaPB.ColumnIdentifierPB> Columns { get; } = new global::System.Collections.Generic.List<PartitionSchemaPB.ColumnIdentifierPB>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class HashBucketSchemaPB : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"columns")]
            public global::System.Collections.Generic.List<PartitionSchemaPB.ColumnIdentifierPB> Columns { get; } = new global::System.Collections.Generic.List<PartitionSchemaPB.ColumnIdentifierPB>();

            [global::ProtoBuf.ProtoMember(2, Name = @"num_buckets", IsRequired = true)]
            public int NumBuckets { get; set; }

            [global::ProtoBuf.ProtoMember(3, Name = @"seed")]
            public uint Seed
            {
                get { return __pbn__Seed.GetValueOrDefault(); }
                set { __pbn__Seed = value; }
            }
            public bool ShouldSerializeSeed() => __pbn__Seed != null;
            public void ResetSeed() => __pbn__Seed = null;
            private uint? __pbn__Seed;

            [global::ProtoBuf.ProtoMember(4, Name = @"hash_algorithm")]
            [global::System.ComponentModel.DefaultValue(HashAlgorithm.UnknownHash)]
            public HashAlgorithm HashAlgorithm
            {
                get { return __pbn__HashAlgorithm ?? HashAlgorithm.UnknownHash; }
                set { __pbn__HashAlgorithm = value; }
            }
            public bool ShouldSerializeHashAlgorithm() => __pbn__HashAlgorithm != null;
            public void ResetHashAlgorithm() => __pbn__HashAlgorithm = null;
            private HashAlgorithm? __pbn__HashAlgorithm;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class PartitionPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"hash_buckets", IsPacked = true)]
        public int[] HashBuckets { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"partition_key_start")]
        public byte[] PartitionKeyStart
        {
            get { return __pbn__PartitionKeyStart; }
            set { __pbn__PartitionKeyStart = value; }
        }
        public bool ShouldSerializePartitionKeyStart() => __pbn__PartitionKeyStart != null;
        public void ResetPartitionKeyStart() => __pbn__PartitionKeyStart = null;
        private byte[] __pbn__PartitionKeyStart;

        [global::ProtoBuf.ProtoMember(3, Name = @"partition_key_end")]
        public byte[] PartitionKeyEnd
        {
            get { return __pbn__PartitionKeyEnd; }
            set { __pbn__PartitionKeyEnd = value; }
        }
        public bool ShouldSerializePartitionKeyEnd() => __pbn__PartitionKeyEnd != null;
        public void ResetPartitionKeyEnd() => __pbn__PartitionKeyEnd = null;
        private byte[] __pbn__PartitionKeyEnd;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ColumnPredicatePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"column")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Column
        {
            get { return __pbn__Column ?? ""; }
            set { __pbn__Column = value; }
        }
        public bool ShouldSerializeColumn() => __pbn__Column != null;
        public void ResetColumn() => __pbn__Column = null;
        private string __pbn__Column;

        [global::ProtoBuf.ProtoMember(2)]
        public Range range
        {
            get { return __pbn__predicate.Is(2) ? ((Range)__pbn__predicate.Object) : default; }
            set { __pbn__predicate = new global::ProtoBuf.DiscriminatedUnionObject(2, value); }
        }
        public bool ShouldSerializerange() => __pbn__predicate.Is(2);
        public void Resetrange() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__predicate, 2);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__predicate;

        [global::ProtoBuf.ProtoMember(3)]
        public Equality equality
        {
            get { return __pbn__predicate.Is(3) ? ((Equality)__pbn__predicate.Object) : default; }
            set { __pbn__predicate = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeequality() => __pbn__predicate.Is(3);
        public void Resetequality() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__predicate, 3);

        [global::ProtoBuf.ProtoMember(4)]
        public IsNotNull is_not_null
        {
            get { return __pbn__predicate.Is(4) ? ((IsNotNull)__pbn__predicate.Object) : default; }
            set { __pbn__predicate = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeis_not_null() => __pbn__predicate.Is(4);
        public void Resetis_not_null() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__predicate, 4);

        [global::ProtoBuf.ProtoMember(5)]
        public InList in_list
        {
            get { return __pbn__predicate.Is(5) ? ((InList)__pbn__predicate.Object) : default; }
            set { __pbn__predicate = new global::ProtoBuf.DiscriminatedUnionObject(5, value); }
        }
        public bool ShouldSerializein_list() => __pbn__predicate.Is(5);
        public void Resetin_list() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__predicate, 5);

        [global::ProtoBuf.ProtoMember(6)]
        public IsNull is_null
        {
            get { return __pbn__predicate.Is(6) ? ((IsNull)__pbn__predicate.Object) : default; }
            set { __pbn__predicate = new global::ProtoBuf.DiscriminatedUnionObject(6, value); }
        }
        public bool ShouldSerializeis_null() => __pbn__predicate.Is(6);
        public void Resetis_null() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__predicate, 6);

        [global::ProtoBuf.ProtoMember(7)]
        public InBloomFilter in_bloom_filter
        {
            get { return __pbn__predicate.Is(7) ? ((InBloomFilter)__pbn__predicate.Object) : default; }
            set { __pbn__predicate = new global::ProtoBuf.DiscriminatedUnionObject(7, value); }
        }
        public bool ShouldSerializein_bloom_filter() => __pbn__predicate.Is(7);
        public void Resetin_bloom_filter() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__predicate, 7);

        [global::ProtoBuf.ProtoContract()]
        public partial class Range : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"lower")]
            public byte[] Lower
            {
                get { return __pbn__Lower; }
                set { __pbn__Lower = value; }
            }
            public bool ShouldSerializeLower() => __pbn__Lower != null;
            public void ResetLower() => __pbn__Lower = null;
            private byte[] __pbn__Lower;

            [global::ProtoBuf.ProtoMember(2, Name = @"upper")]
            public byte[] Upper
            {
                get { return __pbn__Upper; }
                set { __pbn__Upper = value; }
            }
            public bool ShouldSerializeUpper() => __pbn__Upper != null;
            public void ResetUpper() => __pbn__Upper = null;
            private byte[] __pbn__Upper;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class Equality : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"value")]
            public byte[] Value
            {
                get { return __pbn__Value; }
                set { __pbn__Value = value; }
            }
            public bool ShouldSerializeValue() => __pbn__Value != null;
            public void ResetValue() => __pbn__Value = null;
            private byte[] __pbn__Value;

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class InList : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"values")]
            public global::System.Collections.Generic.List<byte[]> Values { get; } = new global::System.Collections.Generic.List<byte[]>();

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class IsNotNull : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class IsNull : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        }

        [global::ProtoBuf.ProtoContract()]
        public partial class InBloomFilter : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"bloom_filters")]
            public global::System.Collections.Generic.List<BlockBloomFilterPB> BloomFilters { get; } = new global::System.Collections.Generic.List<BlockBloomFilterPB>();

            [global::ProtoBuf.ProtoMember(2, Name = @"lower")]
            public byte[] Lower
            {
                get { return __pbn__Lower; }
                set { __pbn__Lower = value; }
            }
            public bool ShouldSerializeLower() => __pbn__Lower != null;
            public void ResetLower() => __pbn__Lower = null;
            private byte[] __pbn__Lower;

            [global::ProtoBuf.ProtoMember(3, Name = @"upper")]
            public byte[] Upper
            {
                get { return __pbn__Upper; }
                set { __pbn__Upper = value; }
            }
            public bool ShouldSerializeUpper() => __pbn__Upper != null;
            public void ResetUpper() => __pbn__Upper = null;
            private byte[] __pbn__Upper;

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class KeyRangePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"start_primary_key")]
        public byte[] StartPrimaryKey
        {
            get { return __pbn__StartPrimaryKey; }
            set { __pbn__StartPrimaryKey = value; }
        }
        public bool ShouldSerializeStartPrimaryKey() => __pbn__StartPrimaryKey != null;
        public void ResetStartPrimaryKey() => __pbn__StartPrimaryKey = null;
        private byte[] __pbn__StartPrimaryKey;

        [global::ProtoBuf.ProtoMember(2, Name = @"stop_primary_key")]
        public byte[] StopPrimaryKey
        {
            get { return __pbn__StopPrimaryKey; }
            set { __pbn__StopPrimaryKey = value; }
        }
        public bool ShouldSerializeStopPrimaryKey() => __pbn__StopPrimaryKey != null;
        public void ResetStopPrimaryKey() => __pbn__StopPrimaryKey = null;
        private byte[] __pbn__StopPrimaryKey;

        [global::ProtoBuf.ProtoMember(3, Name = @"size_bytes_estimates", IsRequired = true)]
        public ulong SizeBytesEstimates { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TableExtraConfigPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"history_max_age_sec")]
        public int HistoryMaxAgeSec
        {
            get { return __pbn__HistoryMaxAgeSec.GetValueOrDefault(); }
            set { __pbn__HistoryMaxAgeSec = value; }
        }
        public bool ShouldSerializeHistoryMaxAgeSec() => __pbn__HistoryMaxAgeSec != null;
        public void ResetHistoryMaxAgeSec() => __pbn__HistoryMaxAgeSec = null;
        private int? __pbn__HistoryMaxAgeSec;

        [global::ProtoBuf.ProtoMember(2, Name = @"maintenance_priority")]
        public int MaintenancePriority
        {
            get { return __pbn__MaintenancePriority.GetValueOrDefault(); }
            set { __pbn__MaintenancePriority = value; }
        }
        public bool ShouldSerializeMaintenancePriority() => __pbn__MaintenancePriority != null;
        public void ResetMaintenancePriority() => __pbn__MaintenancePriority = null;
        private int? __pbn__MaintenancePriority;

    }

    [global::ProtoBuf.ProtoContract()]
    public enum DataTypePB
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_DATA")]
        UnknownData = 999,
        [global::ProtoBuf.ProtoEnum(Name = @"UINT8")]
        Uint8 = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"INT8")]
        Int8 = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"UINT16")]
        Uint16 = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"INT16")]
        Int16 = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"UINT32")]
        Uint32 = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"INT32")]
        Int32 = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"UINT64")]
        Uint64 = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"INT64")]
        Int64 = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"STRING")]
        String = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"BOOL")]
        Bool = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"FLOAT")]
        Float = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"DOUBLE")]
        Double = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"BINARY")]
        Binary = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"UNIXTIME_MICROS")]
        UnixtimeMicros = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"INT128")]
        Int128 = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"DECIMAL32")]
        Decimal32 = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"DECIMAL64")]
        Decimal64 = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"DECIMAL128")]
        Decimal128 = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"IS_DELETED")]
        IsDeleted = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"VARCHAR")]
        Varchar = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"DATE")]
        Date = 20,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum EncodingTypePB
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_ENCODING")]
        UnknownEncoding = 999,
        [global::ProtoBuf.ProtoEnum(Name = @"AUTO_ENCODING")]
        AutoEncoding = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"PLAIN_ENCODING")]
        PlainEncoding = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"PREFIX_ENCODING")]
        PrefixEncoding = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"GROUP_VARINT")]
        GroupVarint = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"RLE")]
        Rle = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"DICT_ENCODING")]
        DictEncoding = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"BIT_SHUFFLE")]
        BitShuffle = 6,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum HmsModePB
    {
        [global::ProtoBuf.ProtoEnum(Name = @"NONE")]
        None = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"DISABLE_HIVE_METASTORE")]
        DisableHiveMetastore = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ENABLE_HIVE_METASTORE")]
        EnableHiveMetastore = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ENABLE_METASTORE_INTEGRATION")]
        EnableMetastoreIntegration = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ExternalConsistencyModePB
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_EXTERNAL_CONSISTENCY_MODE")]
        UnknownExternalConsistencyMode = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"CLIENT_PROPAGATED")]
        ClientPropagated = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"COMMIT_WAIT")]
        CommitWait = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReadModePB
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_READ_MODE")]
        UnknownReadMode = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"READ_LATEST")]
        ReadLatest = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"READ_AT_SNAPSHOT")]
        ReadAtSnapshot = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"READ_YOUR_WRITES")]
        ReadYourWrites = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OrderModePB
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_ORDER_MODE")]
        UnknownOrderMode = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"UNORDERED")]
        Unordered = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"ORDERED")]
        Ordered = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ReplicaSelectionPB
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_REPLICA_SELECTION")]
        UnknownReplicaSelection = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LEADER_ONLY")]
        LeaderOnly = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"CLOSEST_REPLICA")]
        ClosestReplica = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum TableTypePB
    {
        [global::ProtoBuf.ProtoEnum(Name = @"DEFAULT_TABLE")]
        DefaultTable = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"TXN_STATUS_TABLE")]
        TxnStatusTable = 1,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
