// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: client.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Kudu.Client.Protocol.Client
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ScanTokenPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"feature_flags")]
        public global::System.Collections.Generic.List<Feature> FeatureFlags { get; } = new global::System.Collections.Generic.List<Feature>();

        [global::ProtoBuf.ProtoMember(20, Name = @"table_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TableId
        {
            get { return __pbn__TableId ?? ""; }
            set { __pbn__TableId = value; }
        }
        public bool ShouldSerializeTableId() => __pbn__TableId != null;
        public void ResetTableId() => __pbn__TableId = null;
        private string __pbn__TableId;

        [global::ProtoBuf.ProtoMember(2, Name = @"table_name")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TableName
        {
            get { return __pbn__TableName ?? ""; }
            set { __pbn__TableName = value; }
        }
        public bool ShouldSerializeTableName() => __pbn__TableName != null;
        public void ResetTableName() => __pbn__TableName = null;
        private string __pbn__TableName;

        [global::ProtoBuf.ProtoMember(3, Name = @"projected_columns")]
        public global::System.Collections.Generic.List<global::Kudu.Client.Protocol.ColumnSchemaPB> ProjectedColumns { get; } = new global::System.Collections.Generic.List<global::Kudu.Client.Protocol.ColumnSchemaPB>();

        [global::ProtoBuf.ProtoMember(4, Name = @"column_predicates")]
        public global::System.Collections.Generic.List<global::Kudu.Client.Protocol.ColumnPredicatePB> ColumnPredicates { get; } = new global::System.Collections.Generic.List<global::Kudu.Client.Protocol.ColumnPredicatePB>();

        [global::ProtoBuf.ProtoMember(5, Name = @"lower_bound_primary_key")]
        public byte[] LowerBoundPrimaryKey
        {
            get { return __pbn__LowerBoundPrimaryKey; }
            set { __pbn__LowerBoundPrimaryKey = value; }
        }
        public bool ShouldSerializeLowerBoundPrimaryKey() => __pbn__LowerBoundPrimaryKey != null;
        public void ResetLowerBoundPrimaryKey() => __pbn__LowerBoundPrimaryKey = null;
        private byte[] __pbn__LowerBoundPrimaryKey;

        [global::ProtoBuf.ProtoMember(6, Name = @"upper_bound_primary_key")]
        public byte[] UpperBoundPrimaryKey
        {
            get { return __pbn__UpperBoundPrimaryKey; }
            set { __pbn__UpperBoundPrimaryKey = value; }
        }
        public bool ShouldSerializeUpperBoundPrimaryKey() => __pbn__UpperBoundPrimaryKey != null;
        public void ResetUpperBoundPrimaryKey() => __pbn__UpperBoundPrimaryKey = null;
        private byte[] __pbn__UpperBoundPrimaryKey;

        [global::ProtoBuf.ProtoMember(7, Name = @"lower_bound_partition_key")]
        public byte[] LowerBoundPartitionKey
        {
            get { return __pbn__LowerBoundPartitionKey; }
            set { __pbn__LowerBoundPartitionKey = value; }
        }
        public bool ShouldSerializeLowerBoundPartitionKey() => __pbn__LowerBoundPartitionKey != null;
        public void ResetLowerBoundPartitionKey() => __pbn__LowerBoundPartitionKey = null;
        private byte[] __pbn__LowerBoundPartitionKey;

        [global::ProtoBuf.ProtoMember(8, Name = @"upper_bound_partition_key")]
        public byte[] UpperBoundPartitionKey
        {
            get { return __pbn__UpperBoundPartitionKey; }
            set { __pbn__UpperBoundPartitionKey = value; }
        }
        public bool ShouldSerializeUpperBoundPartitionKey() => __pbn__UpperBoundPartitionKey != null;
        public void ResetUpperBoundPartitionKey() => __pbn__UpperBoundPartitionKey = null;
        private byte[] __pbn__UpperBoundPartitionKey;

        [global::ProtoBuf.ProtoMember(9, Name = @"limit")]
        public ulong Limit
        {
            get { return __pbn__Limit.GetValueOrDefault(); }
            set { __pbn__Limit = value; }
        }
        public bool ShouldSerializeLimit() => __pbn__Limit != null;
        public void ResetLimit() => __pbn__Limit = null;
        private ulong? __pbn__Limit;

        [global::ProtoBuf.ProtoMember(10, Name = @"read_mode")]
        [global::System.ComponentModel.DefaultValue(global::Kudu.Client.Protocol.ReadModePB.ReadLatest)]
        public global::Kudu.Client.Protocol.ReadModePB ReadMode
        {
            get { return __pbn__ReadMode ?? global::Kudu.Client.Protocol.ReadModePB.ReadLatest; }
            set { __pbn__ReadMode = value; }
        }
        public bool ShouldSerializeReadMode() => __pbn__ReadMode != null;
        public void ResetReadMode() => __pbn__ReadMode = null;
        private global::Kudu.Client.Protocol.ReadModePB? __pbn__ReadMode;

        [global::ProtoBuf.ProtoMember(11, Name = @"snap_timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SnapTimestamp
        {
            get { return __pbn__SnapTimestamp.GetValueOrDefault(); }
            set { __pbn__SnapTimestamp = value; }
        }
        public bool ShouldSerializeSnapTimestamp() => __pbn__SnapTimestamp != null;
        public void ResetSnapTimestamp() => __pbn__SnapTimestamp = null;
        private ulong? __pbn__SnapTimestamp;

        [global::ProtoBuf.ProtoMember(19, Name = @"snap_start_timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SnapStartTimestamp
        {
            get { return __pbn__SnapStartTimestamp.GetValueOrDefault(); }
            set { __pbn__SnapStartTimestamp = value; }
        }
        public bool ShouldSerializeSnapStartTimestamp() => __pbn__SnapStartTimestamp != null;
        public void ResetSnapStartTimestamp() => __pbn__SnapStartTimestamp = null;
        private ulong? __pbn__SnapStartTimestamp;

        [global::ProtoBuf.ProtoMember(12, Name = @"propagated_timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong PropagatedTimestamp
        {
            get { return __pbn__PropagatedTimestamp.GetValueOrDefault(); }
            set { __pbn__PropagatedTimestamp = value; }
        }
        public bool ShouldSerializePropagatedTimestamp() => __pbn__PropagatedTimestamp != null;
        public void ResetPropagatedTimestamp() => __pbn__PropagatedTimestamp = null;
        private ulong? __pbn__PropagatedTimestamp;

        [global::ProtoBuf.ProtoMember(13, Name = @"cache_blocks")]
        [global::System.ComponentModel.DefaultValue(true)]
        public bool CacheBlocks
        {
            get { return __pbn__CacheBlocks ?? true; }
            set { __pbn__CacheBlocks = value; }
        }
        public bool ShouldSerializeCacheBlocks() => __pbn__CacheBlocks != null;
        public void ResetCacheBlocks() => __pbn__CacheBlocks = null;
        private bool? __pbn__CacheBlocks;

        [global::ProtoBuf.ProtoMember(14, Name = @"fault_tolerant")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool FaultTolerant
        {
            get { return __pbn__FaultTolerant ?? false; }
            set { __pbn__FaultTolerant = value; }
        }
        public bool ShouldSerializeFaultTolerant() => __pbn__FaultTolerant != null;
        public void ResetFaultTolerant() => __pbn__FaultTolerant = null;
        private bool? __pbn__FaultTolerant;

        [global::ProtoBuf.ProtoMember(15, Name = @"batch_size_bytes")]
        public uint BatchSizeBytes
        {
            get { return __pbn__BatchSizeBytes.GetValueOrDefault(); }
            set { __pbn__BatchSizeBytes = value; }
        }
        public bool ShouldSerializeBatchSizeBytes() => __pbn__BatchSizeBytes != null;
        public void ResetBatchSizeBytes() => __pbn__BatchSizeBytes = null;
        private uint? __pbn__BatchSizeBytes;

        [global::ProtoBuf.ProtoMember(16, Name = @"replica_selection")]
        [global::System.ComponentModel.DefaultValue(global::Kudu.Client.Protocol.ReplicaSelectionPB.LeaderOnly)]
        public global::Kudu.Client.Protocol.ReplicaSelectionPB ReplicaSelection
        {
            get { return __pbn__ReplicaSelection ?? global::Kudu.Client.Protocol.ReplicaSelectionPB.LeaderOnly; }
            set { __pbn__ReplicaSelection = value; }
        }
        public bool ShouldSerializeReplicaSelection() => __pbn__ReplicaSelection != null;
        public void ResetReplicaSelection() => __pbn__ReplicaSelection = null;
        private global::Kudu.Client.Protocol.ReplicaSelectionPB? __pbn__ReplicaSelection;

        [global::ProtoBuf.ProtoMember(17, Name = @"scan_request_timeout_ms")]
        public long ScanRequestTimeoutMs
        {
            get { return __pbn__ScanRequestTimeoutMs.GetValueOrDefault(); }
            set { __pbn__ScanRequestTimeoutMs = value; }
        }
        public bool ShouldSerializeScanRequestTimeoutMs() => __pbn__ScanRequestTimeoutMs != null;
        public void ResetScanRequestTimeoutMs() => __pbn__ScanRequestTimeoutMs = null;
        private long? __pbn__ScanRequestTimeoutMs;

        [global::ProtoBuf.ProtoMember(18, Name = @"keep_alive_period_ms")]
        public long KeepAlivePeriodMs
        {
            get { return __pbn__KeepAlivePeriodMs.GetValueOrDefault(); }
            set { __pbn__KeepAlivePeriodMs = value; }
        }
        public bool ShouldSerializeKeepAlivePeriodMs() => __pbn__KeepAlivePeriodMs != null;
        public void ResetKeepAlivePeriodMs() => __pbn__KeepAlivePeriodMs = null;
        private long? __pbn__KeepAlivePeriodMs;

        [global::ProtoBuf.ProtoContract()]
        public enum Feature
        {
            Unknown = 0,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AuthenticationCredentialsPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"authn_token")]
        public global::Kudu.Client.Protocol.Security.SignedTokenPB AuthnToken { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"real_user")]
        [global::System.ComponentModel.DefaultValue("")]
        public string RealUser
        {
            get { return __pbn__RealUser ?? ""; }
            set { __pbn__RealUser = value; }
        }
        public bool ShouldSerializeRealUser() => __pbn__RealUser != null;
        public void ResetRealUser() => __pbn__RealUser = null;
        private string __pbn__RealUser;

        [global::ProtoBuf.ProtoMember(2, Name = @"ca_cert_ders")]
        public global::System.Collections.Generic.List<byte[]> CaCertDers { get; } = new global::System.Collections.Generic.List<byte[]>();

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
