// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: metadata.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Knet.Kudu.Client.Protocol.Consensus
{

    [global::ProtoBuf.ProtoContract()]
    public partial class RaftPeerAttrsPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"promote")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Promote
        {
            get { return __pbn__Promote ?? false; }
            set { __pbn__Promote = value; }
        }
        public bool ShouldSerializePromote() => __pbn__Promote != null;
        public void ResetPromote() => __pbn__Promote = null;
        private bool? __pbn__Promote;

        [global::ProtoBuf.ProtoMember(2, Name = @"replace")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool Replace
        {
            get { return __pbn__Replace ?? false; }
            set { __pbn__Replace = value; }
        }
        public bool ShouldSerializeReplace() => __pbn__Replace != null;
        public void ResetReplace() => __pbn__Replace = null;
        private bool? __pbn__Replace;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class HealthReportPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"overall_health")]
        [global::System.ComponentModel.DefaultValue(HealthStatus.Unknown)]
        public HealthStatus OverallHealth
        {
            get { return __pbn__OverallHealth ?? HealthStatus.Unknown; }
            set { __pbn__OverallHealth = value; }
        }
        public bool ShouldSerializeOverallHealth() => __pbn__OverallHealth != null;
        public void ResetOverallHealth() => __pbn__OverallHealth = null;
        private HealthStatus? __pbn__OverallHealth;

        [global::ProtoBuf.ProtoContract()]
        public enum HealthStatus
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 999,
            [global::ProtoBuf.ProtoEnum(Name = @"FAILED")]
            Failed = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"HEALTHY")]
            Healthy = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"FAILED_UNRECOVERABLE")]
            FailedUnrecoverable = 2,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RaftPeerPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"permanent_uuid")]
        public byte[] PermanentUuid
        {
            get { return __pbn__PermanentUuid; }
            set { __pbn__PermanentUuid = value; }
        }
        public bool ShouldSerializePermanentUuid() => __pbn__PermanentUuid != null;
        public void ResetPermanentUuid() => __pbn__PermanentUuid = null;
        private byte[] __pbn__PermanentUuid;

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue(MemberType.UnknownMemberType)]
        public MemberType member_type
        {
            get { return __pbn__member_type ?? MemberType.UnknownMemberType; }
            set { __pbn__member_type = value; }
        }
        public bool ShouldSerializemember_type() => __pbn__member_type != null;
        public void Resetmember_type() => __pbn__member_type = null;
        private MemberType? __pbn__member_type;

        [global::ProtoBuf.ProtoMember(3, Name = @"last_known_addr")]
        public global::Knet.Kudu.Client.Protocol.HostPortPB LastKnownAddr { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"attrs")]
        public RaftPeerAttrsPB Attrs { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"health_report")]
        public HealthReportPB HealthReport { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Role
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_ROLE")]
            UnknownRole = 999,
            [global::ProtoBuf.ProtoEnum(Name = @"FOLLOWER")]
            Follower = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"LEADER")]
            Leader = 1,
            [global::ProtoBuf.ProtoEnum(Name = @"LEARNER")]
            Learner = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"NON_PARTICIPANT")]
            NonParticipant = 3,
        }

        [global::ProtoBuf.ProtoContract()]
        public enum MemberType
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_MEMBER_TYPE")]
            UnknownMemberType = 999,
            [global::ProtoBuf.ProtoEnum(Name = @"NON_VOTER")]
            NonVoter = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"VOTER")]
            Voter = 1,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RaftConfigPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"opid_index")]
        public long OpidIndex
        {
            get { return __pbn__OpidIndex.GetValueOrDefault(); }
            set { __pbn__OpidIndex = value; }
        }
        public bool ShouldSerializeOpidIndex() => __pbn__OpidIndex != null;
        public void ResetOpidIndex() => __pbn__OpidIndex = null;
        private long? __pbn__OpidIndex;

        [global::ProtoBuf.ProtoMember(2, Name = @"OBSOLETE_local")]
        public bool OBSOLETElocal
        {
            get { return __pbn__OBSOLETElocal.GetValueOrDefault(); }
            set { __pbn__OBSOLETElocal = value; }
        }
        public bool ShouldSerializeOBSOLETElocal() => __pbn__OBSOLETElocal != null;
        public void ResetOBSOLETElocal() => __pbn__OBSOLETElocal = null;
        private bool? __pbn__OBSOLETElocal;

        [global::ProtoBuf.ProtoMember(4, Name = @"unsafe_config_change")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool UnsafeConfigChange
        {
            get { return __pbn__UnsafeConfigChange ?? false; }
            set { __pbn__UnsafeConfigChange = value; }
        }
        public bool ShouldSerializeUnsafeConfigChange() => __pbn__UnsafeConfigChange != null;
        public void ResetUnsafeConfigChange() => __pbn__UnsafeConfigChange = null;
        private bool? __pbn__UnsafeConfigChange;

        [global::ProtoBuf.ProtoMember(3, Name = @"peers")]
        public global::System.Collections.Generic.List<RaftPeerPB> Peers { get; } = new global::System.Collections.Generic.List<RaftPeerPB>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsensusStatePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"current_term", IsRequired = true)]
        public long CurrentTerm { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"leader_uuid")]
        [global::System.ComponentModel.DefaultValue("")]
        public string LeaderUuid
        {
            get { return __pbn__LeaderUuid ?? ""; }
            set { __pbn__LeaderUuid = value; }
        }
        public bool ShouldSerializeLeaderUuid() => __pbn__LeaderUuid != null;
        public void ResetLeaderUuid() => __pbn__LeaderUuid = null;
        private string __pbn__LeaderUuid;

        [global::ProtoBuf.ProtoMember(3, Name = @"committed_config", IsRequired = true)]
        public RaftConfigPB CommittedConfig { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"pending_config")]
        public RaftConfigPB PendingConfig { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsensusMetadataPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"committed_config", IsRequired = true)]
        public RaftConfigPB CommittedConfig { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"current_term", IsRequired = true)]
        public long CurrentTerm { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"voted_for")]
        [global::System.ComponentModel.DefaultValue("")]
        public string VotedFor
        {
            get { return __pbn__VotedFor ?? ""; }
            set { __pbn__VotedFor = value; }
        }
        public bool ShouldSerializeVotedFor() => __pbn__VotedFor != null;
        public void ResetVotedFor() => __pbn__VotedFor = null;
        private string __pbn__VotedFor;

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
