// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: consensus.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Kudu.Client.Protocol.Consensus
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsensusErrorPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, IsRequired = true)]
        public Code code { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"status", IsRequired = true)]
        public global::Kudu.Client.Protocol.AppStatusPB Status { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public enum Code
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN")]
            Unknown = 0,
            [global::ProtoBuf.ProtoEnum(Name = @"INVALID_TERM")]
            InvalidTerm = 2,
            [global::ProtoBuf.ProtoEnum(Name = @"LAST_OPID_TOO_OLD")]
            LastOpidTooOld = 3,
            [global::ProtoBuf.ProtoEnum(Name = @"ALREADY_VOTED")]
            AlreadyVoted = 4,
            [global::ProtoBuf.ProtoEnum(Name = @"NOT_IN_QUORUM")]
            NotInQuorum = 5,
            [global::ProtoBuf.ProtoEnum(Name = @"PRECEDING_ENTRY_DIDNT_MATCH")]
            PrecedingEntryDidntMatch = 6,
            [global::ProtoBuf.ProtoEnum(Name = @"LEADER_IS_ALIVE")]
            LeaderIsAlive = 7,
            [global::ProtoBuf.ProtoEnum(Name = @"CONSENSUS_BUSY")]
            ConsensusBusy = 8,
            [global::ProtoBuf.ProtoEnum(Name = @"CANNOT_PREPARE")]
            CannotPrepare = 9,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeConfigRecordPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tablet_id", IsRequired = true)]
        public byte[] TabletId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"old_config", IsRequired = true)]
        public RaftConfigPB OldConfig { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"new_config", IsRequired = true)]
        public RaftConfigPB NewConfig { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeConfigRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(4, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(1, Name = @"tablet_id", IsRequired = true)]
        public byte[] TabletId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"type")]
        [global::System.ComponentModel.DefaultValue(ChangeConfigType.UnknownChange)]
        public ChangeConfigType Type
        {
            get { return __pbn__Type ?? ChangeConfigType.UnknownChange; }
            set { __pbn__Type = value; }
        }
        public bool ShouldSerializeType() => __pbn__Type != null;
        public void ResetType() => __pbn__Type = null;
        private ChangeConfigType? __pbn__Type;

        [global::ProtoBuf.ProtoMember(3, Name = @"server")]
        public RaftPeerPB Server { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"cas_config_opid_index")]
        public long CasConfigOpidIndex
        {
            get { return __pbn__CasConfigOpidIndex.GetValueOrDefault(); }
            set { __pbn__CasConfigOpidIndex = value; }
        }
        public bool ShouldSerializeCasConfigOpidIndex() => __pbn__CasConfigOpidIndex != null;
        public void ResetCasConfigOpidIndex() => __pbn__CasConfigOpidIndex = null;
        private long? __pbn__CasConfigOpidIndex;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class BulkChangeConfigRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(2, Name = @"tablet_id", IsRequired = true)]
        public byte[] TabletId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"config_changes")]
        public global::System.Collections.Generic.List<ConfigChangeItemPB> ConfigChanges { get; } = new global::System.Collections.Generic.List<ConfigChangeItemPB>();

        [global::ProtoBuf.ProtoMember(4, Name = @"cas_config_opid_index")]
        public long CasConfigOpidIndex
        {
            get { return __pbn__CasConfigOpidIndex.GetValueOrDefault(); }
            set { __pbn__CasConfigOpidIndex = value; }
        }
        public bool ShouldSerializeCasConfigOpidIndex() => __pbn__CasConfigOpidIndex != null;
        public void ResetCasConfigOpidIndex() => __pbn__CasConfigOpidIndex = null;
        private long? __pbn__CasConfigOpidIndex;

        [global::ProtoBuf.ProtoContract()]
        public partial class ConfigChangeItemPB : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"type")]
            [global::System.ComponentModel.DefaultValue(ChangeConfigType.UnknownChange)]
            public ChangeConfigType Type
            {
                get { return __pbn__Type ?? ChangeConfigType.UnknownChange; }
                set { __pbn__Type = value; }
            }
            public bool ShouldSerializeType() => __pbn__Type != null;
            public void ResetType() => __pbn__Type = null;
            private ChangeConfigType? __pbn__Type;

            [global::ProtoBuf.ProtoMember(2, Name = @"peer")]
            public RaftPeerPB Peer { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ChangeConfigResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        public global::Kudu.Client.Protocol.Tserver.TabletServerErrorPB Error { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"new_config")]
        public RaftPeerPB NewConfig { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong Timestamp
        {
            get { return __pbn__Timestamp.GetValueOrDefault(); }
            set { __pbn__Timestamp = value; }
        }
        public bool ShouldSerializeTimestamp() => __pbn__Timestamp != null;
        public void ResetTimestamp() => __pbn__Timestamp = null;
        private ulong? __pbn__Timestamp;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ReplicateMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"id", IsRequired = true)]
        public OpId Id { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize, IsRequired = true)]
        public ulong Timestamp { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"op_type", IsRequired = true)]
        public OperationType OpType { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"write_request")]
        public global::Kudu.Client.Protocol.Tserver.WriteRequestPB WriteRequest { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"alter_schema_request")]
        public global::Kudu.Client.Protocol.Tserver.AlterSchemaRequestPB AlterSchemaRequest { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"change_config_record")]
        public ChangeConfigRecordPB ChangeConfigRecord { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"request_id")]
        public global::Kudu.Client.Protocol.Rpc.RequestIdPB RequestId { get; set; }

        [global::ProtoBuf.ProtoMember(999, Name = @"noop_request")]
        public NoOpRequestPB NoopRequest { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class CommitMsg : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"op_type", IsRequired = true)]
        public OperationType OpType { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"commited_op_id")]
        public OpId CommitedOpId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"result")]
        public global::Kudu.Client.Protocol.Tablet.TxResultPB Result { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class NoOpRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"payload_for_tests")]
        public byte[] PayloadForTests
        {
            get { return __pbn__PayloadForTests; }
            set { __pbn__PayloadForTests = value; }
        }
        public bool ShouldSerializePayloadForTests() => __pbn__PayloadForTests != null;
        public void ResetPayloadForTests() => __pbn__PayloadForTests = null;
        private byte[] __pbn__PayloadForTests;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsensusStatusPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"last_received", IsRequired = true)]
        public OpId LastReceived { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"last_received_current_leader")]
        public OpId LastReceivedCurrentLeader { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"last_committed_idx")]
        public long LastCommittedIdx
        {
            get { return __pbn__LastCommittedIdx.GetValueOrDefault(); }
            set { __pbn__LastCommittedIdx = value; }
        }
        public bool ShouldSerializeLastCommittedIdx() => __pbn__LastCommittedIdx != null;
        public void ResetLastCommittedIdx() => __pbn__LastCommittedIdx = null;
        private long? __pbn__LastCommittedIdx;

        [global::ProtoBuf.ProtoMember(3, Name = @"error")]
        public ConsensusErrorPB Error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VoteRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(6, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(1, Name = @"tablet_id", IsRequired = true)]
        public string TabletId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"candidate_uuid", IsRequired = true)]
        public byte[] CandidateUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"candidate_term", IsRequired = true)]
        public long CandidateTerm { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"candidate_status", IsRequired = true)]
        public ConsensusStatusPB CandidateStatus { get; set; }

        [global::ProtoBuf.ProtoMember(5, Name = @"ignore_live_leader")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IgnoreLiveLeader
        {
            get { return __pbn__IgnoreLiveLeader ?? false; }
            set { __pbn__IgnoreLiveLeader = value; }
        }
        public bool ShouldSerializeIgnoreLiveLeader() => __pbn__IgnoreLiveLeader != null;
        public void ResetIgnoreLiveLeader() => __pbn__IgnoreLiveLeader = null;
        private bool? __pbn__IgnoreLiveLeader;

        [global::ProtoBuf.ProtoMember(7, Name = @"is_pre_election")]
        [global::System.ComponentModel.DefaultValue(false)]
        public bool IsPreElection
        {
            get { return __pbn__IsPreElection ?? false; }
            set { __pbn__IsPreElection = value; }
        }
        public bool ShouldSerializeIsPreElection() => __pbn__IsPreElection != null;
        public void ResetIsPreElection() => __pbn__IsPreElection = null;
        private bool? __pbn__IsPreElection;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class VoteResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"responder_uuid")]
        public byte[] ResponderUuid
        {
            get { return __pbn__ResponderUuid; }
            set { __pbn__ResponderUuid = value; }
        }
        public bool ShouldSerializeResponderUuid() => __pbn__ResponderUuid != null;
        public void ResetResponderUuid() => __pbn__ResponderUuid = null;
        private byte[] __pbn__ResponderUuid;

        [global::ProtoBuf.ProtoMember(2, Name = @"responder_term")]
        public long ResponderTerm
        {
            get { return __pbn__ResponderTerm.GetValueOrDefault(); }
            set { __pbn__ResponderTerm = value; }
        }
        public bool ShouldSerializeResponderTerm() => __pbn__ResponderTerm != null;
        public void ResetResponderTerm() => __pbn__ResponderTerm = null;
        private long? __pbn__ResponderTerm;

        [global::ProtoBuf.ProtoMember(3, Name = @"vote_granted")]
        public bool VoteGranted
        {
            get { return __pbn__VoteGranted.GetValueOrDefault(); }
            set { __pbn__VoteGranted = value; }
        }
        public bool ShouldSerializeVoteGranted() => __pbn__VoteGranted != null;
        public void ResetVoteGranted() => __pbn__VoteGranted = null;
        private bool? __pbn__VoteGranted;

        [global::ProtoBuf.ProtoMember(998, Name = @"consensus_error")]
        public ConsensusErrorPB ConsensusError { get; set; }

        [global::ProtoBuf.ProtoMember(999, Name = @"error")]
        public global::Kudu.Client.Protocol.Tserver.TabletServerErrorPB Error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsensusRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(7, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(1, Name = @"tablet_id", IsRequired = true)]
        public string TabletId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"caller_uuid", IsRequired = true)]
        public byte[] CallerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"caller_term", IsRequired = true)]
        public long CallerTerm { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"preceding_id")]
        public OpId PrecedingId { get; set; }

        [global::ProtoBuf.ProtoMember(8, Name = @"committed_index")]
        public long CommittedIndex
        {
            get { return __pbn__CommittedIndex.GetValueOrDefault(); }
            set { __pbn__CommittedIndex = value; }
        }
        public bool ShouldSerializeCommittedIndex() => __pbn__CommittedIndex != null;
        public void ResetCommittedIndex() => __pbn__CommittedIndex = null;
        private long? __pbn__CommittedIndex;

        [global::ProtoBuf.ProtoMember(5, Name = @"DEPRECATED_committed_index")]
        public OpId DEPRECATEDcommittedindex { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"ops")]
        public global::System.Collections.Generic.List<ReplicateMsg> Ops { get; } = new global::System.Collections.Generic.List<ReplicateMsg>();

        [global::ProtoBuf.ProtoMember(9, Name = @"all_replicated_index")]
        public long AllReplicatedIndex
        {
            get { return __pbn__AllReplicatedIndex.GetValueOrDefault(); }
            set { __pbn__AllReplicatedIndex = value; }
        }
        public bool ShouldSerializeAllReplicatedIndex() => __pbn__AllReplicatedIndex != null;
        public void ResetAllReplicatedIndex() => __pbn__AllReplicatedIndex = null;
        private long? __pbn__AllReplicatedIndex;

        [global::ProtoBuf.ProtoMember(10, Name = @"safe_timestamp", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
        public ulong SafeTimestamp
        {
            get { return __pbn__SafeTimestamp.GetValueOrDefault(); }
            set { __pbn__SafeTimestamp = value; }
        }
        public bool ShouldSerializeSafeTimestamp() => __pbn__SafeTimestamp != null;
        public void ResetSafeTimestamp() => __pbn__SafeTimestamp = null;
        private ulong? __pbn__SafeTimestamp;

        [global::ProtoBuf.ProtoMember(11, Name = @"last_idx_appended_to_leader")]
        public long LastIdxAppendedToLeader
        {
            get { return __pbn__LastIdxAppendedToLeader.GetValueOrDefault(); }
            set { __pbn__LastIdxAppendedToLeader = value; }
        }
        public bool ShouldSerializeLastIdxAppendedToLeader() => __pbn__LastIdxAppendedToLeader != null;
        public void ResetLastIdxAppendedToLeader() => __pbn__LastIdxAppendedToLeader = null;
        private long? __pbn__LastIdxAppendedToLeader;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ConsensusResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"responder_uuid")]
        public byte[] ResponderUuid
        {
            get { return __pbn__ResponderUuid; }
            set { __pbn__ResponderUuid = value; }
        }
        public bool ShouldSerializeResponderUuid() => __pbn__ResponderUuid != null;
        public void ResetResponderUuid() => __pbn__ResponderUuid = null;
        private byte[] __pbn__ResponderUuid;

        [global::ProtoBuf.ProtoMember(2, Name = @"responder_term")]
        public long ResponderTerm
        {
            get { return __pbn__ResponderTerm.GetValueOrDefault(); }
            set { __pbn__ResponderTerm = value; }
        }
        public bool ShouldSerializeResponderTerm() => __pbn__ResponderTerm != null;
        public void ResetResponderTerm() => __pbn__ResponderTerm = null;
        private long? __pbn__ResponderTerm;

        [global::ProtoBuf.ProtoMember(3, Name = @"status")]
        public ConsensusStatusPB Status { get; set; }

        [global::ProtoBuf.ProtoMember(999, Name = @"error")]
        public global::Kudu.Client.Protocol.Tserver.TabletServerErrorPB Error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TransactionStatusPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"op_id", IsRequired = true)]
        public OpId OpId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"tx_type", IsRequired = true)]
        public OperationType TxType { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"running_for_micros", IsRequired = true)]
        public long RunningForMicros { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"description", IsRequired = true)]
        public string Description { get; set; }

        [global::ProtoBuf.ProtoMember(6, Name = @"trace_buffer")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TraceBuffer
        {
            get { return __pbn__TraceBuffer ?? ""; }
            set { __pbn__TraceBuffer = value; }
        }
        public bool ShouldSerializeTraceBuffer() => __pbn__TraceBuffer != null;
        public void ResetTraceBuffer() => __pbn__TraceBuffer = null;
        private string __pbn__TraceBuffer;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetNodeInstanceRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetNodeInstanceResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"node_instance", IsRequired = true)]
        public global::Kudu.Client.Protocol.NodeInstancePB NodeInstance { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RunLeaderElectionRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(1, Name = @"tablet_id", IsRequired = true)]
        public byte[] TabletId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class RunLeaderElectionResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        public global::Kudu.Client.Protocol.Tserver.TabletServerErrorPB Error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaderStepDownRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(1, Name = @"tablet_id", IsRequired = true)]
        public byte[] TabletId { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class LeaderStepDownResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        public global::Kudu.Client.Protocol.Tserver.TabletServerErrorPB Error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLastOpIdRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(2, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(1, Name = @"tablet_id", IsRequired = true)]
        public byte[] TabletId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"opid_type")]
        [global::System.ComponentModel.DefaultValue(OpIdType.ReceivedOpid)]
        public OpIdType OpidType
        {
            get { return __pbn__OpidType ?? OpIdType.ReceivedOpid; }
            set { __pbn__OpidType = value; }
        }
        public bool ShouldSerializeOpidType() => __pbn__OpidType != null;
        public void ResetOpidType() => __pbn__OpidType = null;
        private OpIdType? __pbn__OpidType;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetLastOpIdResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"opid")]
        public OpId Opid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"error")]
        public global::Kudu.Client.Protocol.Tserver.TabletServerErrorPB Error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetConsensusStateRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(2, Name = @"tablet_ids")]
        public global::System.Collections.Generic.List<byte[]> TabletIds { get; } = new global::System.Collections.Generic.List<byte[]>();

        [global::ProtoBuf.ProtoMember(3, Name = @"report_health")]
        [global::System.ComponentModel.DefaultValue(IncludeHealthReport.UnspecifiedHealthReport)]
        public IncludeHealthReport ReportHealth
        {
            get { return __pbn__ReportHealth ?? IncludeHealthReport.UnspecifiedHealthReport; }
            set { __pbn__ReportHealth = value; }
        }
        public bool ShouldSerializeReportHealth() => __pbn__ReportHealth != null;
        public void ResetReportHealth() => __pbn__ReportHealth = null;
        private IncludeHealthReport? __pbn__ReportHealth;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class GetConsensusStateResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"tablets")]
        public global::System.Collections.Generic.List<TabletConsensusInfoPB> Tablets { get; } = new global::System.Collections.Generic.List<TabletConsensusInfoPB>();

        [global::ProtoBuf.ProtoMember(3, Name = @"replica_management_info")]
        public ReplicaManagementInfoPB ReplicaManagementInfo { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"error")]
        public global::Kudu.Client.Protocol.Tserver.TabletServerErrorPB Error { get; set; }

        [global::ProtoBuf.ProtoContract()]
        public partial class TabletConsensusInfoPB : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"tablet_id", IsRequired = true)]
            public byte[] TabletId { get; set; }

            [global::ProtoBuf.ProtoMember(2, Name = @"cstate")]
            public ConsensusStatePB Cstate { get; set; }

        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartTabletCopyRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(5, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(1, Name = @"tablet_id", IsRequired = true)]
        public byte[] TabletId { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"copy_peer_uuid", IsRequired = true)]
        public byte[] CopyPeerUuid { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"copy_peer_addr", IsRequired = true)]
        public global::Kudu.Client.Protocol.HostPortPB CopyPeerAddr { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"caller_term")]
        [global::System.ComponentModel.DefaultValue(-1)]
        public long CallerTerm
        {
            get { return __pbn__CallerTerm ?? -1; }
            set { __pbn__CallerTerm = value; }
        }
        public bool ShouldSerializeCallerTerm() => __pbn__CallerTerm != null;
        public void ResetCallerTerm() => __pbn__CallerTerm = null;
        private long? __pbn__CallerTerm;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class StartTabletCopyResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        public global::Kudu.Client.Protocol.Tserver.TabletServerErrorPB Error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsafeChangeConfigRequestPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"dest_uuid")]
        public byte[] DestUuid
        {
            get { return __pbn__DestUuid; }
            set { __pbn__DestUuid = value; }
        }
        public bool ShouldSerializeDestUuid() => __pbn__DestUuid != null;
        public void ResetDestUuid() => __pbn__DestUuid = null;
        private byte[] __pbn__DestUuid;

        [global::ProtoBuf.ProtoMember(2, Name = @"tablet_id", IsRequired = true)]
        public byte[] TabletId { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"caller_id", IsRequired = true)]
        public byte[] CallerId { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"new_config", IsRequired = true)]
        public RaftConfigPB NewConfig { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class UnsafeChangeConfigResponsePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"error")]
        public global::Kudu.Client.Protocol.Tserver.TabletServerErrorPB Error { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public enum OperationType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_OP")]
        UnknownOp = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"NO_OP")]
        NoOp = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"WRITE_OP")]
        WriteOp = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"ALTER_SCHEMA_OP")]
        AlterSchemaOp = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"CHANGE_CONFIG_OP")]
        ChangeConfigOp = 5,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum DriverType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_DRIVER")]
        UnknownDriver = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"LEADER")]
        Leader = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"REPLICA")]
        Replica = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum ChangeConfigType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_CHANGE")]
        UnknownChange = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"ADD_PEER")]
        AddPeer = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"REMOVE_PEER")]
        RemovePeer = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"MODIFY_PEER")]
        ModifyPeer = 3,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum OpIdType
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNKNOWN_OPID_TYPE")]
        UnknownOpidType = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"RECEIVED_OPID")]
        ReceivedOpid = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"COMMITTED_OPID")]
        CommittedOpid = 2,
    }

    [global::ProtoBuf.ProtoContract()]
    public enum IncludeHealthReport
    {
        [global::ProtoBuf.ProtoEnum(Name = @"UNSPECIFIED_HEALTH_REPORT")]
        UnspecifiedHealthReport = 0,
        [global::ProtoBuf.ProtoEnum(Name = @"EXCLUDE_HEALTH_REPORT")]
        ExcludeHealthReport = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"INCLUDE_HEALTH_REPORT")]
        IncludeHealthReport = 2,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
