// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: token.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Kudu.Client.Protocol.Security
{

    [global::ProtoBuf.ProtoContract()]
    public partial class ColumnPrivilegePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"scan_privilege")]
        public bool ScanPrivilege
        {
            get { return __pbn__ScanPrivilege.GetValueOrDefault(); }
            set { __pbn__ScanPrivilege = value; }
        }
        public bool ShouldSerializeScanPrivilege() => __pbn__ScanPrivilege != null;
        public void ResetScanPrivilege() => __pbn__ScanPrivilege = null;
        private bool? __pbn__ScanPrivilege;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TablePrivilegePB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"table_id")]
        [global::System.ComponentModel.DefaultValue("")]
        public string TableId
        {
            get { return __pbn__TableId ?? ""; }
            set { __pbn__TableId = value; }
        }
        public bool ShouldSerializeTableId() => __pbn__TableId != null;
        public void ResetTableId() => __pbn__TableId = null;
        private string __pbn__TableId;

        [global::ProtoBuf.ProtoMember(2, Name = @"scan_privilege")]
        public bool ScanPrivilege
        {
            get { return __pbn__ScanPrivilege.GetValueOrDefault(); }
            set { __pbn__ScanPrivilege = value; }
        }
        public bool ShouldSerializeScanPrivilege() => __pbn__ScanPrivilege != null;
        public void ResetScanPrivilege() => __pbn__ScanPrivilege = null;
        private bool? __pbn__ScanPrivilege;

        [global::ProtoBuf.ProtoMember(3, Name = @"insert_privilege")]
        public bool InsertPrivilege
        {
            get { return __pbn__InsertPrivilege.GetValueOrDefault(); }
            set { __pbn__InsertPrivilege = value; }
        }
        public bool ShouldSerializeInsertPrivilege() => __pbn__InsertPrivilege != null;
        public void ResetInsertPrivilege() => __pbn__InsertPrivilege = null;
        private bool? __pbn__InsertPrivilege;

        [global::ProtoBuf.ProtoMember(4, Name = @"update_privilege")]
        public bool UpdatePrivilege
        {
            get { return __pbn__UpdatePrivilege.GetValueOrDefault(); }
            set { __pbn__UpdatePrivilege = value; }
        }
        public bool ShouldSerializeUpdatePrivilege() => __pbn__UpdatePrivilege != null;
        public void ResetUpdatePrivilege() => __pbn__UpdatePrivilege = null;
        private bool? __pbn__UpdatePrivilege;

        [global::ProtoBuf.ProtoMember(5, Name = @"delete_privilege")]
        public bool DeletePrivilege
        {
            get { return __pbn__DeletePrivilege.GetValueOrDefault(); }
            set { __pbn__DeletePrivilege = value; }
        }
        public bool ShouldSerializeDeletePrivilege() => __pbn__DeletePrivilege != null;
        public void ResetDeletePrivilege() => __pbn__DeletePrivilege = null;
        private bool? __pbn__DeletePrivilege;

        [global::ProtoBuf.ProtoMember(6, Name = @"column_privileges")]
        [global::ProtoBuf.ProtoMap]
        public global::System.Collections.Generic.Dictionary<int, ColumnPrivilegePB> ColumnPrivileges { get; } = new global::System.Collections.Generic.Dictionary<int, ColumnPrivilegePB>();

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AuthnTokenPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Username
        {
            get { return __pbn__Username ?? ""; }
            set { __pbn__Username = value; }
        }
        public bool ShouldSerializeUsername() => __pbn__Username != null;
        public void ResetUsername() => __pbn__Username = null;
        private string __pbn__Username;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class AuthzTokenPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"username")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Username
        {
            get { return __pbn__Username ?? ""; }
            set { __pbn__Username = value; }
        }
        public bool ShouldSerializeUsername() => __pbn__Username != null;
        public void ResetUsername() => __pbn__Username = null;
        private string __pbn__Username;

        [global::ProtoBuf.ProtoMember(2, Name = @"table_privilege")]
        public TablePrivilegePB TablePrivilege { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TokenPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"expire_unix_epoch_seconds")]
        public long ExpireUnixEpochSeconds
        {
            get { return __pbn__ExpireUnixEpochSeconds.GetValueOrDefault(); }
            set { __pbn__ExpireUnixEpochSeconds = value; }
        }
        public bool ShouldSerializeExpireUnixEpochSeconds() => __pbn__ExpireUnixEpochSeconds != null;
        public void ResetExpireUnixEpochSeconds() => __pbn__ExpireUnixEpochSeconds = null;
        private long? __pbn__ExpireUnixEpochSeconds;

        [global::ProtoBuf.ProtoMember(2, Name = @"incompatible_features")]
        public int[] IncompatibleFeatures { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"authn")]
        public AuthnTokenPB Authn
        {
            get { return __pbn__token.Is(3) ? ((AuthnTokenPB)__pbn__token.Object) : default; }
            set { __pbn__token = new global::ProtoBuf.DiscriminatedUnionObject(3, value); }
        }
        public bool ShouldSerializeAuthn() => __pbn__token.Is(3);
        public void ResetAuthn() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__token, 3);

        private global::ProtoBuf.DiscriminatedUnionObject __pbn__token;

        [global::ProtoBuf.ProtoMember(4, Name = @"authz")]
        public AuthzTokenPB Authz
        {
            get { return __pbn__token.Is(4) ? ((AuthzTokenPB)__pbn__token.Object) : default; }
            set { __pbn__token = new global::ProtoBuf.DiscriminatedUnionObject(4, value); }
        }
        public bool ShouldSerializeAuthz() => __pbn__token.Is(4);
        public void ResetAuthz() => global::ProtoBuf.DiscriminatedUnionObject.Reset(ref __pbn__token, 4);

        [global::ProtoBuf.ProtoContract()]
        public enum Feature
        {
            [global::ProtoBuf.ProtoEnum(Name = @"UNUSED_PLACEHOLDER")]
            UnusedPlaceholder = 999,
        }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class SignedTokenPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"token_data")]
        public byte[] TokenData
        {
            get { return __pbn__TokenData; }
            set { __pbn__TokenData = value; }
        }
        public bool ShouldSerializeTokenData() => __pbn__TokenData != null;
        public void ResetTokenData() => __pbn__TokenData = null;
        private byte[] __pbn__TokenData;

        [global::ProtoBuf.ProtoMember(2, Name = @"signature")]
        public byte[] Signature
        {
            get { return __pbn__Signature; }
            set { __pbn__Signature = value; }
        }
        public bool ShouldSerializeSignature() => __pbn__Signature != null;
        public void ResetSignature() => __pbn__Signature = null;
        private byte[] __pbn__Signature;

        [global::ProtoBuf.ProtoMember(3, Name = @"signing_key_seq_num")]
        public long SigningKeySeqNum
        {
            get { return __pbn__SigningKeySeqNum.GetValueOrDefault(); }
            set { __pbn__SigningKeySeqNum = value; }
        }
        public bool ShouldSerializeSigningKeySeqNum() => __pbn__SigningKeySeqNum != null;
        public void ResetSigningKeySeqNum() => __pbn__SigningKeySeqNum = null;
        private long? __pbn__SigningKeySeqNum;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TokenSigningPrivateKeyPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key_seq_num")]
        public long KeySeqNum
        {
            get { return __pbn__KeySeqNum.GetValueOrDefault(); }
            set { __pbn__KeySeqNum = value; }
        }
        public bool ShouldSerializeKeySeqNum() => __pbn__KeySeqNum != null;
        public void ResetKeySeqNum() => __pbn__KeySeqNum = null;
        private long? __pbn__KeySeqNum;

        [global::ProtoBuf.ProtoMember(2, Name = @"rsa_key_der")]
        public byte[] RsaKeyDer
        {
            get { return __pbn__RsaKeyDer; }
            set { __pbn__RsaKeyDer = value; }
        }
        public bool ShouldSerializeRsaKeyDer() => __pbn__RsaKeyDer != null;
        public void ResetRsaKeyDer() => __pbn__RsaKeyDer = null;
        private byte[] __pbn__RsaKeyDer;

        [global::ProtoBuf.ProtoMember(3, Name = @"expire_unix_epoch_seconds")]
        public long ExpireUnixEpochSeconds
        {
            get { return __pbn__ExpireUnixEpochSeconds.GetValueOrDefault(); }
            set { __pbn__ExpireUnixEpochSeconds = value; }
        }
        public bool ShouldSerializeExpireUnixEpochSeconds() => __pbn__ExpireUnixEpochSeconds != null;
        public void ResetExpireUnixEpochSeconds() => __pbn__ExpireUnixEpochSeconds = null;
        private long? __pbn__ExpireUnixEpochSeconds;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class TokenSigningPublicKeyPB : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"key_seq_num")]
        public long KeySeqNum
        {
            get { return __pbn__KeySeqNum.GetValueOrDefault(); }
            set { __pbn__KeySeqNum = value; }
        }
        public bool ShouldSerializeKeySeqNum() => __pbn__KeySeqNum != null;
        public void ResetKeySeqNum() => __pbn__KeySeqNum = null;
        private long? __pbn__KeySeqNum;

        [global::ProtoBuf.ProtoMember(2, Name = @"rsa_key_der")]
        public byte[] RsaKeyDer
        {
            get { return __pbn__RsaKeyDer; }
            set { __pbn__RsaKeyDer = value; }
        }
        public bool ShouldSerializeRsaKeyDer() => __pbn__RsaKeyDer != null;
        public void ResetRsaKeyDer() => __pbn__RsaKeyDer = null;
        private byte[] __pbn__RsaKeyDer;

        [global::ProtoBuf.ProtoMember(3, Name = @"expire_unix_epoch_seconds")]
        public long ExpireUnixEpochSeconds
        {
            get { return __pbn__ExpireUnixEpochSeconds.GetValueOrDefault(); }
            set { __pbn__ExpireUnixEpochSeconds = value; }
        }
        public bool ShouldSerializeExpireUnixEpochSeconds() => __pbn__ExpireUnixEpochSeconds != null;
        public void ResetExpireUnixEpochSeconds() => __pbn__ExpireUnixEpochSeconds = null;
        private long? __pbn__ExpireUnixEpochSeconds;

    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
