// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: kudu/util/hash.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Knet.Kudu.Client.Protobuf {

  /// <summary>Holder for reflection information generated from kudu/util/hash.proto</summary>
  public static partial class HashReflection {

    #region Descriptor
    /// <summary>File descriptor for kudu/util/hash.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static HashReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRrdWR1L3V0aWwvaGFzaC5wcm90bxIEa3VkdSpSCg1IYXNoQWxnb3JpdGht",
            "EhAKDFVOS05PV05fSEFTSBAAEhEKDU1VUk1VUl9IQVNIXzIQARINCglDSVRZ",
            "X0hBU0gQAhINCglGQVNUX0hBU0gQA0ItCg9vcmcuYXBhY2hlLmt1ZHWqAhlL",
            "bmV0Lkt1ZHUuQ2xpZW50LlByb3RvYnVm"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Knet.Kudu.Client.Protobuf.HashAlgorithm), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// Implemented hash algorithms.
  /// </summary>
  public enum HashAlgorithm {
    [pbr::OriginalName("UNKNOWN_HASH")] UnknownHash = 0,
    [pbr::OriginalName("MURMUR_HASH_2")] MurmurHash2 = 1,
    [pbr::OriginalName("CITY_HASH")] CityHash = 2,
    [pbr::OriginalName("FAST_HASH")] FastHash = 3,
  }

  #endregion

}

#endregion Designer generated code
