// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: kudu/util/pb_util.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Knet.Kudu.Client.Protobuf {

  /// <summary>Holder for reflection information generated from kudu/util/pb_util.proto</summary>
  public static partial class PbUtilReflection {

    #region Descriptor
    /// <summary>File descriptor for kudu/util/pb_util.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PbUtilReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChdrdWR1L3V0aWwvcGJfdXRpbC5wcm90bxIEa3VkdRogZ29vZ2xlL3Byb3Rv",
            "YnVmL2Rlc2NyaXB0b3IucHJvdG8iWwoUQ29udGFpbmVyU3VwSGVhZGVyUEIS",
            "MgoGcHJvdG9zGAEgAigLMiIuZ29vZ2xlLnByb3RvYnVmLkZpbGVEZXNjcmlw",
            "dG9yU2V0Eg8KB3BiX3R5cGUYAiACKAk6NgoGUkVEQUNUEh0uZ29vZ2xlLnBy",
            "b3RvYnVmLkZpZWxkT3B0aW9ucxjRhgMgASgIOgVmYWxzZUItCg9vcmcuYXBh",
            "Y2hlLmt1ZHWqAhlLbmV0Lkt1ZHUuQ2xpZW50LlByb3RvYnVm"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.Reflection.DescriptorReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pb::Extension[] { PbUtilExtensions.REDACT }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Knet.Kudu.Client.Protobuf.ContainerSupHeaderPB), global::Knet.Kudu.Client.Protobuf.ContainerSupHeaderPB.Parser, new[]{ "Protos", "PbType" }, null, null, null, null)
          }));
    }
    #endregion

  }
  /// <summary>Holder for extension identifiers generated from the top level of kudu/util/pb_util.proto</summary>
  public static partial class PbUtilExtensions {
    public static readonly pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool> REDACT =
      new pb::Extension<global::Google.Protobuf.Reflection.FieldOptions, bool>(50001, pb::FieldCodec.ForBool(400008, false));
  }

  #region Messages
  /// <summary>
  /// Supplemental protobuf container header, after the main header (see
  /// pb_util.h for details).
  /// </summary>
  public sealed partial class ContainerSupHeaderPB : pb::IMessage<ContainerSupHeaderPB>
      , pb::IBufferMessage
  {
    private static readonly pb::MessageParser<ContainerSupHeaderPB> _parser = new pb::MessageParser<ContainerSupHeaderPB>(() => new ContainerSupHeaderPB());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<ContainerSupHeaderPB> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Knet.Kudu.Client.Protobuf.PbUtilReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContainerSupHeaderPB() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContainerSupHeaderPB(ContainerSupHeaderPB other) : this() {
      protos_ = other.protos_ != null ? other.protos_.Clone() : null;
      pbType_ = other.pbType_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ContainerSupHeaderPB Clone() {
      return new ContainerSupHeaderPB(this);
    }

    /// <summary>Field number for the "protos" field.</summary>
    public const int ProtosFieldNumber = 1;
    private global::Google.Protobuf.Reflection.FileDescriptorSet protos_;
    /// <summary>
    /// The protobuf schema for the messages expected in this container.
    ///
    /// This schema is complete, that is, it includes all of its dependencies
    /// (i.e. other schemas defined in .proto files imported by this schema's
    /// .proto file).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.Reflection.FileDescriptorSet Protos {
      get { return protos_; }
      set {
        protos_ = value;
      }
    }

    /// <summary>Field number for the "pb_type" field.</summary>
    public const int PbTypeFieldNumber = 2;
    private readonly static string PbTypeDefaultValue = "";

    private string pbType_;
    /// <summary>
    /// The PB message type expected in each data entry in this container. Must
    /// be fully qualified (i.e. kudu.tablet.TabletSuperBlockPB).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PbType {
      get { return pbType_ ?? PbTypeDefaultValue; }
      set {
        pbType_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }
    /// <summary>Gets whether the "pb_type" field is set</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool HasPbType {
      get { return pbType_ != null; }
    }
    /// <summary>Clears the value of the "pb_type" field</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void ClearPbType() {
      pbType_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as ContainerSupHeaderPB);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(ContainerSupHeaderPB other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Protos, other.Protos)) return false;
      if (PbType != other.PbType) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (protos_ != null) hash ^= Protos.GetHashCode();
      if (HasPbType) hash ^= PbType.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
      output.WriteRawMessage(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (protos_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Protos);
      }
      if (HasPbType) {
        output.WriteRawTag(18);
        output.WriteString(PbType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (protos_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Protos);
      }
      if (HasPbType) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PbType);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(ContainerSupHeaderPB other) {
      if (other == null) {
        return;
      }
      if (other.protos_ != null) {
        if (protos_ == null) {
          Protos = new global::Google.Protobuf.Reflection.FileDescriptorSet();
        }
        Protos.MergeFrom(other.Protos);
      }
      if (other.HasPbType) {
        PbType = other.PbType;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
      input.ReadRawMessage(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (protos_ == null) {
              Protos = new global::Google.Protobuf.Reflection.FileDescriptorSet();
            }
            input.ReadMessage(Protos);
            break;
          }
          case 18: {
            PbType = input.ReadString();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
