name: CI

on: [push]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1

jobs:
  linux_build:
    name: Linux build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --no-restore --no-build --configuration Release

  publish:
    name: Publish nuget package
    needs: linux_build
    runs-on: ubuntu-20.04

    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Publish on version change
      uses: rohith/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: src/Knet.Kudu.Client/Knet.Kudu.Client.csproj
        NUGET_KEY: ${{secrets.KUDU_NUGET_API_KEY}}
